import static org.junit.Assert.assertEquals;

import java.io.ByteArrayInputStream;

import org.junit.jupiter.api.Test;

import com.itheima.BattleField.BattleFieldMap;
import com.itheima.BattleFieldTest.BattleFieldRound;
import com.itheima.clock.BattleFieldClock;

class Arena_Of_Valor_Test {

	@Test
	void test() {
		BattleFieldMap battlefield=new BattleFieldMap();
		BattleFieldRound battlefieldround=new BattleFieldRound();
		BattleFieldClock battlefieldclock=new BattleFieldClock();
		battlefieldround.Heroinitialize(battlefield);
		battlefieldclock.ClockDisplay();
		battlefield.MapDisplay();
		battlefield.HeroDisplay();
		ByteArrayInputStream cmd1=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd1);
		battlefieldround.Round(battlefield,battlefieldclock);	
		assertEquals(6,battlefield.Red.get(4).RedLocationY[4]);
		ByteArrayInputStream cmd2=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd2);
		battlefieldround.Round(battlefield,battlefieldclock);
		assertEquals(52,battlefield.Blue.get(0).BlueLocationY[0]);
		ByteArrayInputStream cmd3=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd3);
		battlefieldround.Round(battlefield,battlefieldclock);
		assertEquals(7,battlefield.Red.get(4).RedLocationY[4]);
		ByteArrayInputStream cmd4=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd4);
		battlefieldround.Round(battlefield,battlefieldclock);
		assertEquals(51,battlefield.Blue.get(0).BlueLocationY[0]);
		ByteArrayInputStream cmd5=new ByteArrayInputStream("move l down".getBytes());
		battlefieldround.setIn(cmd5);
		battlefieldround.Round(battlefield,battlefieldclock);
		assertEquals(9,battlefield.Red.get(4).RedLocationX[4]);
		ByteArrayInputStream cmd6=new ByteArrayInputStream("move h up".getBytes());
		battlefieldround.setIn(cmd6);
		battlefieldround.Round(battlefield,battlefieldclock);
		assertEquals(7,battlefield.Blue.get(0).BlueLocationX[0]);
		ByteArrayInputStream cmd7=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd7);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd8=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd8);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd9=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd9);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd10=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd10);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd11=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd11);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd13=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd13);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd15=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd15);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd16=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd16);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd17=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd17);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd18=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd18);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd19=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd19);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd20=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd20);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd21=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd21);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd22=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd22);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd23=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd23);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd24=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd24);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd25=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd25);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd26=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd26);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd27=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd27);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd28=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd28);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd29=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd29);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd30=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd30);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd31=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd31);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd32=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd32);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd33=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd33);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd34=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd34);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd35=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd35);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd36=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd36);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd37=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd37);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd38=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd38);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd39=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd39);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd40=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd40);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd41=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd41);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd42=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd42);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd43=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd43);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd44=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd44);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd45=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd45);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd46=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd46);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd47=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd47);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd48=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd48);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd49=new ByteArrayInputStream("move l right".getBytes());
		battlefieldround.setIn(cmd49);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd50=new ByteArrayInputStream("move h left".getBytes());
		battlefieldround.setIn(cmd50);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd51=new ByteArrayInputStream("move l up".getBytes());
		battlefieldround.setIn(cmd51);
		battlefieldround.Round(battlefield,battlefieldclock);	
		ByteArrayInputStream cmd52=new ByteArrayInputStream("move h down".getBytes());
		battlefieldround.setIn(cmd52);
		battlefieldround.Round(battlefield,battlefieldclock);
		ByteArrayInputStream cmd53=new ByteArrayInputStream("attack activeattack 5 1".getBytes());
		battlefieldround.setIn(cmd53);
		battlefieldround.Round(battlefield,battlefieldclock);
		assertEquals(2647,battlefield.Blue.get(0).HP);
		assertEquals(410,battlefield.Red.get(4).MP);
		ByteArrayInputStream cmd54=new ByteArrayInputStream("attack normalattack 1 5".getBytes());
		battlefieldround.setIn(cmd54);
		battlefieldround.Round(battlefield,battlefieldclock);
		assertEquals(3371,battlefield.Red.get(4).HP);
		ByteArrayInputStream cmd55=new ByteArrayInputStream("attack passionattack 5 1".getBytes());
		battlefieldround.setIn(cmd55);
		battlefieldround.Round(battlefield,battlefieldclock);
		assertEquals(2137,battlefield.Blue.get(0).HP);
	}
}
